### ISSUE TITLE
求数据集

### ISSUE THREAD

**Issue by sunyilgdx** [Suspect-wu/ccks_2020_el#1]
请问可以分享一下数据集吗，官方赛道已经结束了

**Comment by Suspect-wu** [comment]
可以啊 我找找 应该还在

**Comment by Suspect-wu** [comment]
> 请问可以分享一下数据集吗，官方赛道已经结束了
可以啊 我找找 应该还在

**Comment by Suspect-wu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Suspect-wu/ccks_2020_el"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 下午3:15
收件人:&nbsp;"Suspect-wu/ccks_2020_el"<ccks_2020_el@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Suspect-wu/ccks_2020_el] 求数据集 (#1)





 
请问可以分享一下数据集吗，官方赛道已经结束了
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

._.DS_Store (120B, 2020年11月19日 15:51 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=77346332eec9999d203b800e4036544d54570254025205041a0c540a031b525600524e535452054f54575702500e075656055250663d664c681a27613965120d4551630f&code=74c2f6fb




._CCKS 2020 Entity Linking License.docx (252B, 2020年11月19日 15:51 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=6a31396162c7c6cc213eda5d40380b1c53085b0504085a571b035b5007150d5255071403550e5d1e50075b03020c09020f520a00661f391d69727a2a35180b0304011924084c50474f1175080853505d51117508055d5740531f5d0e0540390e&code=619af893




._eval.py (176B, 2020年11月19日 15:51 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0732353162cc9dcf2e3dd60d1433501f0f0b00005107060914540c55571e56070e0b180851075a1d0e000003570a00515b030d03323a621e665743505e1d1249390f&code=925123b0




._README (384B, 2020年11月19日 15:51 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5b623337e69acc9c716dd00b4064014c54530705075107514b5703045e49075750041e555256504e035201055306010056030301666c334d39307676222976635b&code=fb37fd3c




CCKS 2020 Entity Linking License.docx (47.4K, 2020年11月19日 15:51 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=6c343365a77bc79e213bd05912390a4e0e03075304005e551b00020756140c5155511e04500e5e4c0e55075404005c0400560b50341c3822757f604506090a5116715d115d4d41417a5d5d0e5d575f417a5d50005a4a5d4f525b501d3404&code=643e498a




README (286B, 2020年11月19日 15:51 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=58626662d7c79dca746d855e1339501a06535600025f07504e0404500614560301554b5a020f54185b5b5450030a040c56565351353f62672623222f70395f&code=cbfb59b5




train.json (25.71M, 2020年11月19日 15:51 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=59363661c4c201cd7139d55d4064571c02040e5154025d0b4b0105040449515250501b005f5d5d1e500407510201000b020e0603666e654714575f0f480e165c08360b&code=f66afde3




.DS_Store (6.0K, 2020年11月19日 15:52 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0836363398d09cce2139d50f4237511e045553565c5400081b0f0402561a570455051b0a5c03501c010207525c03560350010650643e631f7265696010581154360b&code=6663d7c1




eval.py (6.2K, 2020年11月19日 15:52 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0537323542d79a9b2e38d1094530574b0c52010154025202140f5603541d5153090e1f0d5a545d490e0e5651505254055d530b53633765014f565e1b13496559&code=9725c0ed




kb.json (221.34M, 2020年12月19日 15:52 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0b666632c7e41d932069850e4065054e07540457505004561a5e000a0348030202074b535e550e4c0455525357550e53015405536662370a55480c41090b375c&code=7ff2fe7a




test.json (2.68M, 2020年11月19日 15:52 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5a623533a31ae099736dd60f13320749015106505157545f4953010b001f01515650180b5405044b0052000b0302510452535751353b35120111411d5f415a08645f&code=db53525f




dev.json (2.94M, 2020年11月19日 15:52 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0a6564354bc3e69c206a87094035044c0e070556545352531a035701531802555307490d070d024e00005d5052570e570f505254663d360752134a5f155a58630a&code=7ed5f56c

**Comment by sunyilgdx** [comment]
非常感谢！
